# Generated by Django 5.2.17 on 2026-09-30 18:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Butce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic_butcesi', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Başlangıç Bütçesi')),
                ('guncel_butce', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Güncel Bütçe')),
                ('son_islem_tarihi', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Son İşlem Tarihi')),
                ('aciklama', models.CharField(blank=True, default='', max_length=255, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Bütçe',
                'verbose_name_plural': 'Bütçeler',
                'ordering': ['-son_islem_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='CariHesap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unvan', models.CharField(max_length=255, verbose_name='Ad / Unvan')),
                ('tur', models.CharField(choices=[('musteri', 'Müşteri'), ('tedarikci', 'Tedarikçi'), ('diger', 'Diğer Cari')], default='musteri', max_length=20, verbose_name='Cari Türü')),
                ('yetkili', models.CharField(blank=True, default='', max_length=150, verbose_name='Yetkili Kişi')),
                ('telefon', models.CharField(blank=True, default='', max_length=50, verbose_name='Telefon')),
                ('eposta', models.EmailField(blank=True, default='', max_length=150, verbose_name='E-posta')),
                ('adres', models.TextField(blank=True, default='', verbose_name='Adres')),
                ('vergi_dairesi', models.CharField(blank=True, default='', max_length=100, verbose_name='Vergi Dairesi')),
                ('vergi_no', models.CharField(blank=True, default='', max_length=50, verbose_name='Vergi No / TC Kimlik No')),
                ('baslangic_bakiyesi', models.DecimalField(decimal_places=2, default=0, help_text='Pozitif ise bizden alacaklı, negatif ise bize borçludur.', max_digits=12, verbose_name='Başlangıç Bakiyesi (TL)')),
                ('guncel_bakiye', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Güncel Bakiye (TL)')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
            ],
            options={
                'verbose_name': 'Cari Hesap',
                'verbose_name_plural': 'Cari Hesaplar',
                'ordering': ['unvan'],
            },
        ),
        migrations.CreateModel(
            name='GiderKategorisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('aciklama', models.CharField(blank=True, default='', max_length=255, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Gider Kategorisi',
                'verbose_name_plural': 'Gider Kategorileri',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='HaftalikPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('detay', models.TextField(blank=True, default='', verbose_name='Detay')),
                ('baslangic_tarihi', models.DateField(null=True, verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(null=True, verbose_name='Bitiş Tarihi')),
                ('durum', models.CharField(choices=[('tamamlandi', 'Tamamlandı'), ('bekliyor', 'Bekliyor')], default='bekliyor', max_length=20, verbose_name='Durum')),
            ],
            options={
                'verbose_name': 'Haftalık Plan',
                'verbose_name_plural': 'Haftalık Planlar',
                'ordering': ['-baslangic_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Kasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasa_adi', models.CharField(help_text='Örn: Merkez Nakit Kasa, Ziraat Bankası Vadesiz vb.', max_length=150, verbose_name='Kasa / Hesap Adı')),
                ('para_birimi', models.CharField(default='TL', max_length=10, verbose_name='Para Birimi')),
                ('aciklama', models.CharField(blank=True, default='', max_length=255, verbose_name='Açıklama')),
                ('baslangic_bakiyesi', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Başlangıç Bakiyesi')),
                ('guncel_bakiye', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Güncel Bakiye')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
            ],
            options={
                'verbose_name': 'Kasa / Banka',
                'verbose_name_plural': 'Kasalar & Bankalar',
                'ordering': ['kasa_adi'],
            },
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('adet_miktar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Adet / Miktar')),
                ('birim', models.CharField(default='Adet', max_length=50, verbose_name='Birim')),
                ('alis_fiyati', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Alış Fiyatı (TL)')),
                ('alim_tarihi', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Alım Tarihi')),
                ('son_guncelleme', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Stok',
                'verbose_name_plural': 'Stoklar',
                'ordering': ['urun_adi'],
            },
        ),
        migrations.CreateModel(
            name='VergiAyarlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdv_orani', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='KDV Oranı (%)')),
                ('gelir_vergisi_orani', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Gelir Vergisi Oranı (%)')),
                ('kurumlar_vergisi_orani', models.DecimalField(decimal_places=2, default=25, max_digits=5, verbose_name='Kurumlar Vergisi Oranı (%)')),
                ('stopaj_orani', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Stopaj Oranı (%)')),
                ('kdv_dahil', models.BooleanField(default=True, help_text='İşaretliyse girilen tutarlar KDV dahil kabul edilir.', verbose_name='Tutarlar KDV Dahil')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Vergi Ayarı',
                'verbose_name_plural': 'Vergi Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Alacak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (TL)')),
                ('islem_tarihi', models.DateField(default=django.utils.timezone.now, help_text='Alacağın oluştuğu / kaydedildiği tarih', null=True, verbose_name='İşlem Tarihi')),
                ('tahsil_tarihi', models.DateField(blank=True, null=True, verbose_name='Tahsil Tarihi')),
                ('kimden', models.CharField(max_length=200, verbose_name='Kimden')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('durum', models.CharField(choices=[('tahsil_edildi', 'Tahsil Edildi'), ('bekliyor', 'Bekliyor')], default='bekliyor', max_length=20, verbose_name='Durum')),
                ('butce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alacaklar', to='yonetim.butce', verbose_name='İlgili Bütçe')),
            ],
            options={
                'verbose_name': 'Alacak',
                'verbose_name_plural': 'Alacaklar',
                'ordering': ['-islem_tarihi', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CekSenet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('cek', 'Çek'), ('senet', 'Senet')], default='cek', max_length=10, verbose_name='Evrak Türü')),
                ('yon', models.CharField(choices=[('alinan', 'Alınan (Müşteri Evrağı)'), ('verilen', 'Verilen (Kendi Evrağımız)')], default='alinan', max_length=10, verbose_name='Yönü')),
                ('portfoy_no', models.CharField(max_length=50, verbose_name='Portföy / Seri No')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (TL)')),
                ('vade_tarihi', models.DateField(null=True, verbose_name='Vade Tarihi')),
                ('keside_tarihi', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Keşide / Düzenleme Tarihi')),
                ('banka_sube', models.CharField(blank=True, default='', max_length=150, verbose_name='Banka / Şube Bilgisi')),
                ('durum', models.CharField(choices=[('portfoyde', 'Portföyde'), ('tahsil_edildi', 'Tahsil Edildi / Ödendi'), ('ciro_edildi', 'Ciro Edildi'), ('karsiliksiz_protestolu', 'Karşılıksız / Protestolu')], default='portfoyde', max_length=30, verbose_name='Durum')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('cari_hesap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cek_senetler', to='yonetim.carihesap', verbose_name='İlgili Cari Hesap')),
            ],
            options={
                'verbose_name': 'Çek / Senet',
                'verbose_name_plural': 'Çekler & Senetler',
                'ordering': ['vade_tarihi', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura_no', models.CharField(max_length=60, verbose_name='Fatura No')),
                ('tur', models.CharField(choices=[('gelen', 'Gelen Fatura (Alış / Gider)'), ('giden', 'Giden Fatura (Satış / Gelir)')], max_length=10, verbose_name='Fatura Türü')),
                ('tarih', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Fatura Tarihi')),
                ('vade_tarihi', models.DateField(blank=True, null=True, verbose_name='Vade Tarihi')),
                ('matrah', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Matrah (KDV Hariç Tutar)')),
                ('kdv_orani', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='KDV Oranı (%)')),
                ('kdv_tutari', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='KDV Tutarı')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Toplam Tutar')),
                ('odenen_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ödenen Tutar')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('kismi_odendi', 'Kısmi Ödendi'), ('odendi', 'Ödendi')], default='bekliyor', max_length=20, verbose_name='Durum')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('fatura_dosyasi', models.FileField(blank=True, null=True, upload_to='faturalar/%Y/%m/', verbose_name='Fatura Dosyası / PDF')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('cari_hesap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturalar', to='yonetim.carihesap', verbose_name='Cari Hesap')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturalar',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Fis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar')),
                ('tarih', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Tarih')),
                ('kategori', models.CharField(max_length=100, verbose_name='Kategori')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('fis_gorseli', models.ImageField(blank=True, null=True, upload_to='fisler/%Y/%m/', verbose_name='Fiş Görseli')),
                ('butce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fisler', to='yonetim.butce', verbose_name='İlgili Bütçe')),
            ],
            options={
                'verbose_name': 'Fiş',
                'verbose_name_plural': 'Fişler',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IsletmeGideri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (TL)')),
                ('kdv_orani', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='KDV Oranı (%)')),
                ('odeme_tarihi', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Ödeme Tarihi')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('belge', models.FileField(blank=True, null=True, upload_to='giderler/%Y/%m/', verbose_name='Belge / Fiş Görseli')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='giderler', to='yonetim.giderkategorisi', verbose_name='Gider Kategorisi')),
                ('kasa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giderler', to='yonetim.kasa', verbose_name='Ödenen Kasa / Banka')),
            ],
            options={
                'verbose_name': 'İşletme Gideri',
                'verbose_name_plural': 'İşletme Giderleri',
                'ordering': ['-odeme_tarihi', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KasaHareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_turu', models.CharField(choices=[('giris', 'Giriş (Tahsilat / Gelir)'), ('cikis', 'Çıkış (Ödeme / Gider)')], max_length=10, verbose_name='İşlem Türü')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (TL)')),
                ('tarih', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='İşlem Tarihi')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('cari_hesap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kasa_hareketleri', to='yonetim.carihesap', verbose_name='İlişkili Cari Hesap')),
                ('fatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kasa_hareketleri', to='yonetim.fatura', verbose_name='İlişkili Fatura')),
                ('isletme_gideri', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kasa_hareketleri', to='yonetim.isletmegideri', verbose_name='İlişkili İşletme Gideri')),
                ('kasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hareketler', to='yonetim.kasa', verbose_name='İlgili Kasa / Banka')),
            ],
            options={
                'verbose_name': 'Kasa Hareketi',
                'verbose_name_plural': 'Kasa Hareketleri',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar (TL)')),
                ('islem_tarihi', models.DateField(default=django.utils.timezone.now, help_text='Ödeme kaydının oluşturulduğu / işlemin yapıldığı tarih', null=True, verbose_name='İşlem Tarihi')),
                ('vade_tarihi', models.DateField(help_text='Paranın ne zaman ödeneceği', null=True, verbose_name='Ödeme Tarihi')),
                ('kime', models.CharField(max_length=200, verbose_name='Kime')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('durum', models.CharField(choices=[('odendi', 'Ödendi'), ('bekliyor', 'Bekliyor')], default='bekliyor', max_length=20, verbose_name='Durum')),
                ('butce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odemeler', to='yonetim.butce', verbose_name='İlgili Bütçe')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-islem_tarihi', '-id'],
            },
        ),
    ]
