# Generated by Django 5.2.17 on 2026-09-29 14:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Butce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic_butcesi', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Başlangıç Bütçesi')),
                ('guncel_butce', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Güncel Bütçe')),
                ('son_islem_tarihi', models.DateField(default=django.utils.timezone.now, verbose_name='Son İşlem Tarihi')),
                ('aciklama', models.CharField(blank=True, default='', max_length=255, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Bütçe',
                'verbose_name_plural': 'Bütçeler',
                'ordering': ['-son_islem_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='HaftalikPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('detay', models.TextField(blank=True, default='', verbose_name='Detay')),
                ('baslangic_tarihi', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('bitis_tarihi', models.DateField(verbose_name='Bitiş Tarihi')),
                ('durum', models.CharField(choices=[('tamamlandi', 'Tamamlandı'), ('bekliyor', 'Bekliyor')], default='bekliyor', max_length=20, verbose_name='Durum')),
            ],
            options={
                'verbose_name': 'Haftalık Plan',
                'verbose_name_plural': 'Haftalık Planlar',
                'ordering': ['-baslangic_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('adet_miktar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Adet / Miktar')),
                ('birim', models.CharField(default='Adet', max_length=50, verbose_name='Birim')),
                ('son_guncelleme', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Stok',
                'verbose_name_plural': 'Stoklar',
                'ordering': ['urun_adi'],
            },
        ),
        migrations.CreateModel(
            name='Alacak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar')),
                ('tarih', models.DateField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('kimden', models.CharField(max_length=200, verbose_name='Kimden')),
                ('butce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alacaklar', to='yonetim.butce', verbose_name='İlgili Bütçe')),
            ],
            options={
                'verbose_name': 'Alacak',
                'verbose_name_plural': 'Alacaklar',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Fis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar')),
                ('tarih', models.DateField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('kategori', models.CharField(max_length=100, verbose_name='Kategori')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('fis_gorseli', models.ImageField(blank=True, null=True, upload_to='fisler/%Y/%m/', verbose_name='Fiş Görseli')),
                ('butce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fisler', to='yonetim.butce', verbose_name='İlgili Bütçe')),
            ],
            options={
                'verbose_name': 'Fiş',
                'verbose_name_plural': 'Fişler',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Odeme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar')),
                ('tarih', models.DateField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('aciklama', models.TextField(blank=True, default='', verbose_name='Açıklama')),
                ('kime', models.CharField(max_length=200, verbose_name='Kime')),
                ('butce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odemeler', to='yonetim.butce', verbose_name='İlgili Bütçe')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'ordering': ['-tarih', '-id'],
            },
        ),
    ]
